use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .join("../../..")
        .canonicalize()
        .expect("failed to resolve workspace root");
    let stage_root = manifest_dir.join(".runtime-bundle");
    let target_dir = build_target_dir().expect("failed to resolve cargo target dir");

    println!(
        "cargo:rerun-if-changed={}",
        workspace_root.join("services").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        workspace_root.join("fixtures").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        workspace_root.join(".venv").display()
    );
    println!("cargo:rerun-if-env-changed=ROUGHCUT_DESKTOP_STAGE_RUNTIME");
    println!("cargo:rerun-if-env-changed=ROUGHCUT_DESKTOP_PYTHON_HOME");
    println!("cargo:rerun-if-env-changed=ROUGHCUT_DESKTOP_SITE_PACKAGES");
    println!("cargo:rerun-if-env-changed=ROUGHCUT_DESKTOP_FFMPEG");
    println!("cargo:rerun-if-env-changed=ROUGHCUT_DESKTOP_FFPROBE");

    prepare_stage_root(&stage_root).expect("failed to prepare runtime bundle staging root");
    stage_static_resources(&workspace_root, &stage_root)
        .expect("failed to stage bundled resources");
    clean_copied_bundle_resources(&target_dir).expect("failed to clean copied bundle resources");

    if should_stage_runtime() {
        stage_packaged_runtime(&workspace_root, &stage_root)
            .expect("failed to stage packaged runtime");
    }

    tauri_build::build()
}

fn should_stage_runtime() -> bool {
    env::var("ROUGHCUT_DESKTOP_STAGE_RUNTIME")
        .map(|value| matches!(value.as_str(), "1" | "true" | "yes" | "on"))
        .unwrap_or_else(|_| {
            env::var("PROFILE")
                .map(|profile| profile == "release")
                .unwrap_or(false)
        })
}

fn build_target_dir() -> io::Result<PathBuf> {
    let out_dir = PathBuf::from(
        env::var("OUT_DIR")
            .map_err(|_| io::Error::new(io::ErrorKind::NotFound, "missing OUT_DIR"))?,
    );
    out_dir
        .parent()
        .and_then(Path::parent)
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "failed to derive target dir"))
}

fn clean_copied_bundle_resources(target_dir: &Path) -> io::Result<()> {
    for relative in ["runtime", "services", "fixtures"] {
        let path = target_dir.join(relative);
        if path.exists() {
            fs::remove_dir_all(&path)?;
        }
    }
    Ok(())
}

fn prepare_stage_root(stage_root: &Path) -> io::Result<()> {
    fs::create_dir_all(stage_root.join("services"))?;
    fs::create_dir_all(stage_root.join("fixtures"))?;
    fs::create_dir_all(stage_root.join("runtime/bin"))?;
    fs::create_dir_all(stage_root.join("runtime/lib"))?;
    fs::create_dir_all(stage_root.join("runtime/python/bin"))?;
    write_text(
        &stage_root.join("runtime/README.txt"),
        "This directory is generated by build.rs for packaged desktop builds.\n",
    )
}

fn stage_static_resources(workspace_root: &Path, stage_root: &Path) -> io::Result<()> {
    copy_tree(
        &workspace_root.join("services"),
        &stage_root.join("services"),
    )
    .map_err(|error| {
        io::Error::new(
            error.kind(),
            format!(
                "failed to copy services {} -> {}: {error}",
                workspace_root.join("services").display(),
                stage_root.join("services").display()
            ),
        )
    })?;
    copy_tree(
        &workspace_root.join("fixtures"),
        &stage_root.join("fixtures"),
    )
    .map_err(|error| {
        io::Error::new(
            error.kind(),
            format!(
                "failed to copy fixtures {} -> {}: {error}",
                workspace_root.join("fixtures").display(),
                stage_root.join("fixtures").display()
            ),
        )
    })?;
    Ok(())
}

fn stage_packaged_runtime(workspace_root: &Path, stage_root: &Path) -> io::Result<()> {
    let runtime_root = stage_root.join("runtime");
    if runtime_root.exists() {
        fs::remove_dir_all(&runtime_root)?;
    }
    fs::create_dir_all(runtime_root.join("bin"))?;
    fs::create_dir_all(runtime_root.join("python/bin"))?;

    let python_home = detect_python_home(workspace_root)?;
    let python_executable_name = detect_python_executable_name(workspace_root)?;
    let site_packages = detect_site_packages(workspace_root)?;
    let ffmpeg = detect_binary_path("ROUGHCUT_DESKTOP_FFMPEG", "/opt/homebrew/bin/ffmpeg")?;
    let ffprobe = detect_binary_path("ROUGHCUT_DESKTOP_FFPROBE", "/opt/homebrew/bin/ffprobe")?;
    let media_dependency_closure =
        collect_non_system_dependencies(&[ffmpeg.clone(), ffprobe.clone()]).map_err(|error| {
            io::Error::new(
                error.kind(),
                format!("failed to inspect ffmpeg/ffprobe dependencies: {error}"),
            )
        })?;

    let staged_python_home = runtime_root.join("python/python-home");
    copy_tree(&python_home, &staged_python_home).map_err(|error| {
        io::Error::new(
            error.kind(),
            format!(
                "failed to copy python home {} -> {}: {error}",
                python_home.display(),
                staged_python_home.display()
            ),
        )
    })?;
    copy_tree(&site_packages, &runtime_root.join("python/site-packages")).map_err(|error| {
        io::Error::new(
            error.kind(),
            format!(
                "failed to copy site-packages {} -> {}: {error}",
                site_packages.display(),
                runtime_root.join("python/site-packages").display()
            ),
        )
    })?;
    copy_runtime_binary(&ffmpeg, &runtime_root.join("bin/ffmpeg")).map_err(|error| {
        io::Error::new(
            error.kind(),
            format!(
                "failed to copy ffmpeg {} -> {}: {error}",
                ffmpeg.display(),
                runtime_root.join("bin/ffmpeg").display()
            ),
        )
    })?;
    copy_runtime_binary(&ffprobe, &runtime_root.join("bin/ffprobe")).map_err(|error| {
        io::Error::new(
            error.kind(),
            format!(
                "failed to copy ffprobe {} -> {}: {error}",
                ffprobe.display(),
                runtime_root.join("bin/ffprobe").display()
            ),
        )
    })?;
    for (alias_name, dylib) in &media_dependency_closure {
        copy_runtime_library(dylib, &runtime_root.join("lib").join(alias_name)).map_err(
            |error| {
                io::Error::new(
                    error.kind(),
                    format!(
                        "failed to copy runtime library {} -> {}: {error}",
                        dylib.display(),
                        runtime_root.join("lib").join(alias_name).display()
                    ),
                )
            },
        )?;
    }
    rewrite_media_binary_load_paths(
        &runtime_root.join("bin/ffmpeg"),
        &runtime_root.join("bin/ffprobe"),
        &runtime_root.join("lib"),
    )
    .map_err(|error| {
        io::Error::new(
            error.kind(),
            format!("failed to rewrite bundled media binary load paths: {error}"),
        )
    })?;
    write_python_wrapper(
        &runtime_root.join("python/bin/python3"),
        &python_executable_name,
    )?;
    write_text(
        &runtime_root.join("manifest.txt"),
        &format!(
            "python_home={}\nsite_packages={}\nffmpeg={}\nffprobe={}\n",
            python_home.display(),
            site_packages.display(),
            ffmpeg.display(),
            ffprobe.display()
        ),
    )?;

    Ok(())
}

fn detect_python_home(workspace_root: &Path) -> io::Result<PathBuf> {
    if let Ok(value) = env::var("ROUGHCUT_DESKTOP_PYTHON_HOME") {
        let path = PathBuf::from(value);
        if path.exists() {
            return Ok(path);
        }
    }

    let venv_python = workspace_root.join(".venv/bin/python3");
    let resolved = venv_python.canonicalize()?;
    resolved
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "failed to derive python home"))
}

fn detect_python_executable_name(workspace_root: &Path) -> io::Result<String> {
    let venv_python = workspace_root.join(".venv/bin/python3");
    let resolved = venv_python.canonicalize()?;
    resolved
        .file_name()
        .and_then(|name| name.to_str())
        .map(ToOwned::to_owned)
        .ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::NotFound,
                "failed to derive python executable name",
            )
        })
}

fn detect_site_packages(workspace_root: &Path) -> io::Result<PathBuf> {
    if let Ok(value) = env::var("ROUGHCUT_DESKTOP_SITE_PACKAGES") {
        let path = PathBuf::from(value);
        if path.exists() {
            return Ok(path);
        }
    }

    let lib_dir = workspace_root.join(".venv/lib");
    let mut candidates = fs::read_dir(&lib_dir)?
        .filter_map(Result::ok)
        .map(|entry| entry.path().join("site-packages"))
        .filter(|path| path.exists())
        .collect::<Vec<_>>();
    candidates.sort();
    candidates
        .into_iter()
        .next()
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "failed to find site-packages"))
}

fn detect_binary_path(env_name: &str, default_path: &str) -> io::Result<PathBuf> {
    if let Ok(value) = env::var(env_name) {
        let path = PathBuf::from(value);
        if path.exists() {
            return Ok(path);
        }
    }
    let path = PathBuf::from(default_path);
    if path.exists() {
        Ok(path)
    } else {
        Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!("missing runtime binary: {}", path.display()),
        ))
    }
}

fn collect_non_system_dependencies(roots: &[PathBuf]) -> io::Result<BTreeMap<String, PathBuf>> {
    let mut queue = roots
        .iter()
        .map(|path| resolve_real_path(path))
        .collect::<io::Result<Vec<PathBuf>>>()?;
    let mut seen = std::collections::BTreeSet::new();
    let mut dylibs = BTreeMap::new();

    while let Some(path) = queue.pop() {
        if !seen.insert(path.clone()) {
            continue;
        }
        for dep in otool_dependencies(&path)? {
            if !dep.starts_with("/opt/homebrew/") {
                continue;
            }
            let dep_source_path = Path::new(&dep);
            let dep_path = resolve_real_path(dep_source_path)?;
            if dep.ends_with(".dylib") {
                let alias_name = file_name(dep_source_path)?.to_string_lossy().into_owned();
                dylibs.insert(alias_name, dep_path.clone());
            }
            if !seen.contains(&dep_path) {
                queue.push(dep_path);
            }
        }
    }

    Ok(dylibs)
}

fn resolve_real_path(path: &Path) -> io::Result<PathBuf> {
    path.canonicalize()
}

fn otool_dependencies(path: &Path) -> io::Result<Vec<String>> {
    let output = Command::new("otool").arg("-L").arg(path).output()?;
    if !output.status.success() {
        return Err(io::Error::other(format!(
            "otool -L failed for {}",
            path.display()
        )));
    }

    Ok(String::from_utf8_lossy(&output.stdout)
        .lines()
        .skip(1)
        .filter_map(|line| {
            let trimmed = line.trim();
            if trimmed.is_empty() {
                return None;
            }
            trimmed
                .split_once(" (compatibility")
                .map(|(dep, _)| dep.trim().to_string())
        })
        .collect())
}

fn file_name(path: &Path) -> io::Result<&std::ffi::OsStr> {
    path.file_name()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "path is missing file name"))
}

fn copy_tree(source: &Path, target: &Path) -> io::Result<()> {
    if target.exists() {
        fs::remove_dir_all(target)?;
    }
    fs::create_dir_all(target)?;
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let source_path = entry.path();
        let target_path = target.join(entry.file_name());
        copy_path(&source_path, &target_path)?;
    }
    Ok(())
}

fn copy_path(source: &Path, target: &Path) -> io::Result<()> {
    let metadata = fs::symlink_metadata(source)?;
    if metadata.file_type().is_symlink() {
        let resolved = match source.canonicalize() {
            Ok(path) => path,
            Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(()),
            Err(error) => return Err(error),
        };
        return copy_path(&resolved, target);
    }
    if metadata.is_dir() {
        fs::create_dir_all(target)?;
        for entry in fs::read_dir(source)? {
            let entry = entry?;
            let child_source = entry.path();
            let child_target = target.join(entry.file_name());
            copy_path(&child_source, &child_target).map_err(|error| {
                io::Error::new(
                    error.kind(),
                    format!(
                        "failed to copy {} -> {}: {error}",
                        child_source.display(),
                        child_target.display()
                    ),
                )
            })?;
        }
        return Ok(());
    }
    copy_file(source, target)
}

fn copy_file(source: &Path, target: &Path) -> io::Result<()> {
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::copy(source, target)?;
    #[cfg(unix)]
    {
        let mode = fs::metadata(source)?.permissions().mode() | 0o200;
        fs::set_permissions(target, fs::Permissions::from_mode(mode))?;
    }
    Ok(())
}

fn copy_runtime_binary(source: &Path, target: &Path) -> io::Result<()> {
    copy_file(source, target)?;
    #[cfg(unix)]
    {
        fs::set_permissions(target, fs::Permissions::from_mode(0o644))?;
    }
    Ok(())
}

fn copy_runtime_library(source: &Path, target: &Path) -> io::Result<()> {
    copy_file(source, target)?;
    #[cfg(unix)]
    {
        fs::set_permissions(target, fs::Permissions::from_mode(0o755))?;
    }
    Ok(())
}

fn rewrite_media_binary_load_paths(
    ffmpeg_path: &Path,
    ffprobe_path: &Path,
    lib_dir: &Path,
) -> io::Result<()> {
    let binaries = [ffmpeg_path, ffprobe_path];
    let dylibs = fs::read_dir(lib_dir)?
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("dylib"))
        .collect::<Vec<_>>();

    for dylib in &dylibs {
        let dylib_name = file_name(dylib)?.to_string_lossy().into_owned();
        run_install_name_tool(dylib, &["-id".into(), format!("@loader_path/{dylib_name}")])?;
    }

    for binary in binaries {
        for dep in otool_dependencies(binary)? {
            if !dep.starts_with("/opt/homebrew/") {
                continue;
            }
            let dep_name = file_name(Path::new(&dep))?.to_string_lossy().into_owned();
            run_install_name_tool(
                binary,
                &[
                    "-change".into(),
                    dep,
                    format!("@executable_path/../lib/{dep_name}"),
                ],
            )?;
        }
    }

    for dylib in &dylibs {
        for dep in otool_dependencies(dylib)? {
            if !dep.starts_with("/opt/homebrew/") {
                continue;
            }
            let dep_name = file_name(Path::new(&dep))?.to_string_lossy().into_owned();
            run_install_name_tool(
                dylib,
                &["-change".into(), dep, format!("@loader_path/{dep_name}")],
            )?;
        }
    }

    for dylib in &dylibs {
        ad_hoc_codesign(dylib)?;
    }
    ad_hoc_codesign(ffmpeg_path)?;
    ad_hoc_codesign(ffprobe_path)?;

    Ok(())
}

fn run_install_name_tool(path: &Path, args: &[String]) -> io::Result<()> {
    let output = Command::new("install_name_tool")
        .args(args)
        .arg(path)
        .output()?;
    if output.status.success() {
        return Ok(());
    }
    Err(io::Error::other(format!(
        "install_name_tool failed for {}: {}",
        path.display(),
        String::from_utf8_lossy(&output.stderr).trim()
    )))
}

fn ad_hoc_codesign(path: &Path) -> io::Result<()> {
    let output = Command::new("codesign")
        .args(["--force", "--sign", "-"])
        .arg(path)
        .output()?;
    if output.status.success() {
        return Ok(());
    }
    Err(io::Error::other(format!(
        "codesign failed for {}: {}",
        path.display(),
        String::from_utf8_lossy(&output.stderr).trim()
    )))
}

fn write_python_wrapper(wrapper_path: &Path, python_executable_name: &str) -> io::Result<()> {
    let wrapper = format!(
        "#!/bin/sh\nset -eu\nSCRIPT_DIR=\"$(CDPATH= cd -- \"$(dirname \"$0\")\" && pwd)\"\nRESOURCE_ROOT=\"$(CDPATH= cd -- \"$SCRIPT_DIR/../../..\" && pwd)\"\nPYTHON_HOME=\"$SCRIPT_DIR/../python-home\"\nSITE_PACKAGES=\"$SCRIPT_DIR/../site-packages\"\nexport PYTHONHOME=\"$PYTHON_HOME\"\nif [ -n \"${{PYTHONPATH:-}}\" ]; then\n  export PYTHONPATH=\"$RESOURCE_ROOT:$SITE_PACKAGES:$PYTHONPATH\"\nelse\n  export PYTHONPATH=\"$RESOURCE_ROOT:$SITE_PACKAGES\"\nfi\nexec \"$PYTHON_HOME/bin/{}\" \"$@\"\n",
        python_executable_name
    );
    write_text(wrapper_path, &wrapper)?;
    #[cfg(unix)]
    {
        fs::set_permissions(wrapper_path, fs::Permissions::from_mode(0o755))?;
    }
    Ok(())
}

fn write_text(path: &Path, content: &str) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)
}
